import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    backgroundColor: theme.colors.surface,
  },
  backBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIcon: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: 'bold',
  },
  headerTitle: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  exportButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.borderRadius.round,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
  },
  neonButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 10,
  },
  exportButtonText: {
    color: theme.colors.text,
    fontWeight: 'bold',
    fontSize: 13,
  },
  previewArea: {
    flex: 3.5, 
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  videoPlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoIconText: {
    fontSize: 48,
    marginBottom: theme.spacing.md,
  },
  undoRedoOverlay: {
    position: 'absolute',
    right: theme.spacing.md,
    top: theme.spacing.md,
    flexDirection: 'row',
  },
  actionIconBtn: {
    marginLeft: theme.spacing.md,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  undoRedoText: {
    color: '#ffffff',
    fontSize: 22,
  },
  previewPlaceholderText: {
    color: theme.colors.textSecondary,
    fontSize: 16,
    textAlign: 'center',
    paddingHorizontal: theme.spacing.lg,
  },
  // BARRE CENTRALE
  middleControlBar: {
    height: 50,
    backgroundColor: theme.colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.md,
    borderBottomWidth: 1,
    borderColor: '#222222',
  },
  timeText: {
    color: theme.colors.text,
    fontSize: 12,
    fontFamily: 'monospace',
  },
  centerControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  middleCircleBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.surfaceLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: theme.spacing.xs,
  },
  activeMiddleBtn: {
    backgroundColor: theme.colors.primary,
  },
  disabledMiddleBtn: {
    opacity: 0.4,
  },
  middleBtnText: {
    color: '#ffffff',
    fontSize: 14,
  },
  quickAddBtn: {
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    borderColor: theme.colors.primary,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 4,
    borderRadius: 4,
  },
  quickAddBtnText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  // TIMELINE
  timelineArea: {
    flex: 2.5, 
    backgroundColor: '#141414',
    position: 'relative',
  },
  timeRuler: {
    flexDirection: 'row',
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderColor: '#222222',
  },
  rulerTime: {
    color: '#555555',
    fontSize: 10,
    fontFamily: 'monospace',
    width: 100, // Largeur fixe correspondant à la taille du bloc clip + transition
    textAlign: 'left',
  },
  timelineScroll: {
    alignItems: 'flex-start',
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: Dimensions.get('window').width / 2, // Padding centralisé ici
  },
  timelineMargin: {
    width: Dimensions.get('window').width / 2, 
  },
  emptyTimelineBtn: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderStyle: 'dashed',
    borderWidth: 1.5,
    borderColor: '#444444',
    borderRadius: 8,
    margin: theme.spacing.md,
  },
  emptyTimelineIcon: {
    fontSize: 28,
    marginBottom: theme.spacing.xs,
  },
  emptyTimelineText: {
    color: theme.colors.textSecondary,
    fontSize: 14,
  },
  clipBlock: {
    height: 60,
    backgroundColor: '#262626',
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#444444',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'flex-end',
  },
  selectedClipBlock: {
    borderColor: '#ffffff', // Bordure blanche de sélection
  },
  clipFilmStrip: {
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  clipFilmThumbnail: {
    width: 55,
    height: '100%',
    resizeMode: 'cover',
    opacity: 0.6,
  },
  videoClipThumbnail: {
    backgroundColor: '#1b1b1b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoThumbnailIcon: {
    fontSize: 20,
  },
  clipBlockLabel: {
    color: '#ffffff',
    fontSize: 8,
    backgroundColor: 'rgba(0,0,0,0.65)',
    paddingHorizontal: 2,
    position: 'absolute',
    bottom: 2,
    left: 2,
    right: 2,
    textAlign: 'center',
    zIndex: 5,
  },
  keyframeDotContainer: {
    position: 'absolute',
    top: 2,
    right: 4,
    flexDirection: 'row',
    zIndex: 10,
  },
  timelineKeyframeDiamond: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
    marginHorizontal: 1,
    textShadowColor: '#000',
    textShadowRadius: 2,
  },
  // ZOOM CONTROLS
  zoomControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 6,
    backgroundColor: '#0D0D0D',
    borderBottomWidth: 1,
    borderBottomColor: '#222222',
  },
  zoomTitleText: {
    color: '#888888',
    fontSize: 10,
    marginRight: 8,
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  zoomBtn: {
    backgroundColor: '#222222',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    marginRight: 6,
  },
  activeZoomBtn: {
    backgroundColor: theme.colors.primary,
  },
  zoomBtnText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  // TRACKS
  tracksContainer: {
    flexDirection: 'column',
  },
  videoTrackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 70,
  },
  audioTrackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 40,
    borderTopWidth: 1,
    borderTopColor: '#222222',
    backgroundColor: 'rgba(0,0,0,0.15)',
    position: 'relative',
    marginTop: 8,
  },
  audioClipBlock: {
    position: 'absolute',
    height: 32,
    backgroundColor: '#10B981',
    borderRadius: 6,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderLeftWidth: 3,
    borderLeftColor: '#047857',
    overflow: 'hidden',
  },
  audioClipText: {
    color: '#ffffff',
    fontSize: 8,
    fontWeight: 'bold',
    zIndex: 10,
    position: 'absolute',
    left: 6,
    top: 2,
  },
  waveformContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: '100%',
    width: '100%',
    paddingBottom: 4,
    paddingLeft: 4,
  },
  waveformBar: {
    width: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    marginHorizontal: 1.5,
    borderRadius: 1,
  },
  emptyAudioTrackText: {
    color: '#444444',
    fontSize: 10,
    fontStyle: 'italic',
    paddingLeft: 20,
  },
  // PROPERTIES & KEYFRAMES PANEL
  propertiesPanelContainer: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 8,
  },
  propertiesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#222222',
    paddingBottom: 8,
    marginBottom: 8,
  },
  propertiesPanelTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  timelineKeyframeBtn: {
    backgroundColor: '#2A2A2A',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#444444',
  },
  activeKeyframeBtn: {
    backgroundColor: theme.colors.primary,
    borderColor: '#ffffff',
  },
  keyframeBtnText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  slidersScrollView: {
    flex: 1,
  },
  sliderWrapper: {
    marginBottom: 10,
  },
  sliderLabel: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    marginBottom: 4,
  },
  sliderTrackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sliderStepBtn: {
    width: 28,
    height: 28,
    backgroundColor: '#2A2A2A',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sliderStepText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sliderBarContainer: {
    flex: 1,
    height: 6,
    backgroundColor: '#222222',
    borderRadius: 3,
    marginHorizontal: 12,
    overflow: 'hidden',
  },
  sliderBarFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
  },
  // TRANSITION
  transitionIndicator: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#333333',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: theme.spacing.xs,
    borderWidth: 1,
    borderColor: '#444444',
  },
  activeTransitionIndicator: {
    backgroundColor: theme.colors.primary,
    borderColor: '#ffffff',
  },
  transitionIndicatorText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  playhead: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: Dimensions.get('window').width / 2,
    alignItems: 'center',
  },
  playheadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  playheadLine: {
    width: 1.5,
    flex: 1,
    backgroundColor: '#ffffff',
  },
  // BOTTOM TOOLS
  bottomToolsBar: {
    height: 80,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
  },
  toolsScroll: {
    alignItems: 'center',
    paddingHorizontal: theme.spacing.md,
  },
  formatBadge: {
    width: 32,
    height: 50,
    backgroundColor: '#333333',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
  },
  formatBadgeText: {
    color: '#ffffff',
    fontSize: 8,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  toolBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: theme.spacing.md,
    minWidth: 50,
  },
  disabledToolBtn: {
    opacity: 0.3,
  },
  toolIcon: {
    fontSize: 22,
    color: '#ffffff',
    marginBottom: 4,
  },
  toolLabel: {
    color: theme.colors.textSecondary,
    fontSize: 10,
  },
  editingPanelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: theme.spacing.md,
  },
  backToMainBtn: {
    width: 36,
    height: 36,
    backgroundColor: theme.colors.primary,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.sm,
  },
  backToMainArrow: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  transitionOption: {
    backgroundColor: theme.colors.surfaceLight,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    borderRadius: 8,
    marginHorizontal: theme.spacing.xs,
    borderColor: theme.colors.primary,
    borderWidth: 1,
  },
  transitionOptionText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  textModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    padding: 20,
  },
  textModalContent: {
    backgroundColor: theme.colors.surface,
    padding: 20,
    borderRadius: 12,
  },
  textInput: {
    backgroundColor: '#333',
    color: '#FFF',
    fontSize: 18,
    padding: 15,
    borderRadius: 8,
  },
  exportModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  exportModalContent: {
    width: '80%',
    alignItems: 'center',
  },
  exportTitle: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 30,
  },
  progressBarContainer: {
    width: '100%',
    height: 12,
    backgroundColor: '#333',
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 15,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
  },
  exportProgressText: {
    color: theme.colors.primary,
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  exportSubText: {
    color: '#CCC',
    fontSize: 14,
    marginBottom: 5,
  },
  exportWarning: {
    color: '#888',
    fontSize: 12,
    fontStyle: 'italic',
  },
  videoPlayerContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  cameraGridLineH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    top: '50%',
  },
  cameraGridLineV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    left: '50%',
  },
  recBadgeRow: {
    position: 'absolute',
    top: theme.spacing.md,
    left: theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  recDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#666',
    marginRight: 6,
  },
  recDotActive: {
    backgroundColor: '#EF4444',
  },
  recText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  centerPlayIconContainer: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  centerPlayIcon: {
    color: '#FFF',
    fontSize: 20,
    marginLeft: 2,
  },
  videoBottomInfo: {
    position: 'absolute',
    bottom: theme.spacing.md,
    left: theme.spacing.md,
    right: theme.spacing.md,
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 8,
    borderRadius: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  videoInfoTitle: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: 'bold',
    flex: 1,
    marginRight: 10,
  },
  videoTimecode: {
    color: theme.colors.primary,
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  liveAudioBarsRow: {
    position: 'absolute',
    top: theme.spacing.md,
    left: theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 30,
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 6,
    borderRadius: 6,
    zIndex: 100,
  },
  liveAudioBar: {
    width: 3,
    backgroundColor: theme.colors.primary,
    marginHorizontal: 1,
    borderRadius: 1.5,
  },
});
